 export const ACTION_TYPES = {
   SET_CURRENT_USER: 'SET_CURRENT_USER',
   SET_USER_ERROR: 'SET_USER_ERROR',
   SET_USER_REQUEST: 'SET_USER_REQUEST',
   GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
   ADD_TO_CART: 'ADD_TO_CART',
 };
